### ISSUE TITLE
Receiving Error: Unable to process command '::set-env 

### ISSUE THREAD

**Issue by jontreynes** [Azure/get-keyvault-secrets#20]
I am recieving the below error when running the task on ubuntu-latest. I see core 1.2.6 is already updated in package-lock.json.

```
    - name: Get KeyVault Secrets
      uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: "mykv"
        secrets: 'ARM-CLIENT-ID, ARM-CLIENT-SECRET, ARM-SUBSCRIPTION-ID, ARM-TENANT-ID'
      id: get_secret_action
```

```
Error: Unable to process command '::set-env name=AZURE_HTTP_USER_AGENT,::GITHUBACTIONS_GetKeyVaultSecrets_**' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
